### ISSUE TITLE
Training Prophet with regressors

### ISSUE THREAD

**Issue by MGodgildieva** [tinkoff-ai/etna#1099]
### Checklist

- [X] I have searched the issues.
- [X] I have searched the docs.

### ❓ What is the issue?

How to use regressors when training model?

Adding parameter 'regressors' to train function returns an error: 

TypeError: fit() got an unexpected keyword argument 'regressors'

In documentation there is no such parameter but in prophet.py there is: 

def fit(self, df: pd.DataFrame, regressors: List[str]) -> "_ProphetAdapter":

Also a possibility to tune regressors' parameters would be useful!

**Comment by Mr-Geekman** [comment]
Can you please tell us what version of etna are you using?

**Comment by Mr-Geekman** [comment]
The line `def fit(self, df: pd.DataFrame, regressors: List[str]) -> "_ProphetAdapter"` is written for class `_ProphetAdapter` which is not public. We use `_ProphetAdapter` for adapting prophet into our library.

There is public class `ProphetModel` and it has the following signature for `fit`:
```python
def fit(self, ts: TSDataset)
```
As you can see, there is no `regressors` parameter. Because parameter `ts` can hold information about regressors. 

To provide `ProphetModel` with regressors you should make sure that there are some regressors inside `ts` that you are passing into `fit`. You can check it by calling `ts.regressors`. To learn how to put regressors into `ts` you can read the tutorial [Regressors and exogenous data](https://github.com/tinkoff-ai/etna/blob/master/examples/exogenous_data.ipynb). TLDR; you can pass them during creation of `TSDataset` or add transforms that make regressors.
