### ISSUE TITLE
[BUG] I get ImportError: cannot import name 'PytorchForecastingDatasetBuilder' from 'etna.models.nn.utils' 

### ISSUE THREAD

**Issue by dimka11** [tinkoff-ai/etna#1182]
### 🐛 Bug Report

I did try this tutorial https://etna-docs.netlify.app/tutorials/nn_examples

But get error:

`ImportError: cannot import name 'PytorchForecastingDatasetBuilder' from 'etna.models.nn.utils' `

where

`from etna.models.nn.utils import PytorchForecastingDatasetBuilder`

### Expected behavior

import without error

### How To Reproduce

2. Run '....'
3. See error

### Environment

Windows 11  Python 3.9.2
latest pytorch-forecasting installed

### Checklist

- [X] Bug appears at the latest library version

**Comment by Mr-Geekman** [comment]
Hi, I'm very sorry that haven't noticed this issue earlier. 

I suspect that the problem is connected to the fact, that documentation is hosted for the master branch. But at the moment of issue creation the change with `PytorchForecastingDatasetBuilder` wasn't released.

It is now released, you should try to update the etna version up to 2.0.0.
