### ISSUE TITLE
Unpin pytorch-forecasting dependency on specific version

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#387]
### 🚀 Feature Request

Currently we pin specific version of  pytorch-forecasting (0.8.5 to be exact).
Probably we should specify only minimum and maximum versions

### Motivation

Library installation in existing environments would cause less dependency problems.

### Proposal

- Check new releases of pytorch-forecasting for api updates and bug fixes
- If there's no radical changes it seems we can unpeen version

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by alex-hse-repository** [comment]
1. The next version after 0.8.5 is 0.9.0. which changes the API [see](https://pytorch-forecasting.readthedocs.io/en/stable/CHANGELOG.html). Both changes influence `PytorchForecastingTransform` constructor. So, as I understand, we can only use 0.8.5 or ^0.9.0 with changing the  `PytorchForecastingTransform` constructor
2. In addition since 0.9.1 python ^3.7.1 is required, when we have ">=3.7.0, <3.10.0"
3. Also, since 0.9.1 pandas ^1.3.0 is required

Create a draft with changes for ^0.9.0 versions
